version: '2.4'

services:
  file_repo:
    image: file_repo:latest
    container_name: file_repo
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    ports:
      - 80:80
    environment:
        PYTHONUNBUFFERED: "1"
        FILE_MIN_SIZE: 10
        SERVER_PAIR: example.net
    volumes:
      - /data:/data:rw
